---
title: "gtex_data_transformations"
author: "Prashit Parikh"
date: "3/31/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
chooseCRANmirror(graphics=FLASE, ind=1)
knitr::opts_chunk$set(echo = TRUE)
#install.packages("readr")
library(readr)
#install.packages("dplyr")
library(dplyr)
#install.packages("tibble")
library(tibble)
#BiocManager::install("recount3")
library(recount3)
recount3_cache_rm()
options(recount3_url = "http://duffel.rail.bio/recount3")
human_projects<-available_projects()
#install.packages("tidyr")
library(tidyr)
#install.pckages("stringr")
library(stringr)
```

```{r}
gtex_pull <- subset(human_projects, file_source == "gtex" & project_type == "data_sources")

gtex_transformed_counts <- list()
projects_local <- c("ADIPOSE_TISSUE", "MUSCLE", "BLOOD_VESSEL", "HEART", "OVARY", "UTERUS",  
"VAGINA", "BREAST", "SKIN", "SALIVARY_GLAND", "BRAIN", "ADRENAL_GLAND", "THYROID",
  "LUNG", "SPLEEN", "PANCREAS", "ESOPHAGUS", "STOMACH", 
"COLON", "SMALL_INTESTINE", "PROSTATE", "TESTIS", "NERVE", "PITUITARY",      
"BLOOD", "LIVER", "KIDNEY",   "CERVIX_UTERI", "FALLOPIAN_TUBE", "BLADDER", 
"STUDY_NA", "BONE_MARROW")

for (i in projects_local) {
  rse_gene = create_rse(subset(gtex_pull, project == i), annotation = "gencode_v29")
  assays(rse_gene)$counts <- transform_counts(rse_gene)
  
  rse_gene_counts <- recount::getTPM(rse_gene) %>% data.frame()
  rse_gene_counts <- rownames_to_column(rse_gene_counts, var = "gene_id")
  
  gtex_transformed_counts[[i]] <- rse_gene_counts
}

adipose_tissue_counts <- gtex_transformed_counts$ADIPOSE_TISSUE %>% as.data.frame()
muscle_counts <- gtex_transformed_counts$MUSCLE %>% as.data.frame()
blood_vessel_counts <- gtex_transformed_counts$BLOOD_VESSEL %>% as.data.frame()
heart_counts <- gtex_transformed_counts$HEART %>% as.data.frame()
ovary_counts <- gtex_transformed_counts$OVARY %>% as.data.frame()
uterus_counts <- gtex_transformed_counts$UTERUS %>% as.data.frame()
vagina_counts <- gtex_transformed_counts$VAGINA %>% as.data.frame()
breast_counts <- gtex_transformed_counts$BREAST %>% as.data.frame()
skin_counts <- gtex_transformed_counts$SKIN %>% as.data.frame()
salivary_gland_counts <- gtex_transformed_counts$SALIVARY_GLAND %>% as.data.frame()
brain_counts <- gtex_transformed_counts$BRAIN %>% as.data.frame()
adrenal_gland_counts <- gtex_transformed_counts$ADRENAL_GLAND %>% as.data.frame()
thyroid_counts <- gtex_transformed_counts$THYROID %>% as.data.frame()
lung_counts <- gtex_transformed_counts$LUNG %>% as.data.frame()
spleen_counts <- gtex_transformed_counts$SPLEEN %>% as.data.frame()
pancreas_counts <- gtex_transformed_counts$PANCREAS %>% as.data.frame()
esophagus_counts <- gtex_transformed_counts$ESOPHAGUS %>% as.data.frame()
stomach_counts <- gtex_transformed_counts$STOMACH %>% as.data.frame()
colon_counts <- gtex_transformed_counts$COLON %>% as.data.frame()
small_intestine_counts <- gtex_transformed_counts$SMALL_INTESTINE %>% as.data.frame()
prostate_counts <- gtex_transformed_counts$PROSTATE %>% as.data.frame()
testis_counts <- gtex_transformed_counts$TESTIS %>% as.data.frame()
nerve_counts <- gtex_transformed_counts$NERVE %>% as.data.frame()
pituitary_counts <- gtex_transformed_counts$PITUITARY %>% as.data.frame()
blood_counts <- gtex_transformed_counts$BLOOD %>% as.data.frame()
liver_counts <- gtex_transformed_counts$LIVER %>% as.data.frame()
kidney_counts <- gtex_transformed_counts$KIDNEY %>% as.data.frame()
cervix_uteri_counts <- gtex_transformed_counts$CERVIX_UTERI %>% as.data.frame()
fallopian_tube_counts <- gtex_transformed_counts$FALLOPIAN_TUBE %>% as.data.frame()
bladder_counts <- gtex_transformed_counts$BLADDER %>% as.data.frame()
study_na_counts <- gtex_transformed_counts$STUDY_NA %>% as.data.frame() #Not using as it only accounts for 14 samples in the 2019 eyeIntegration and we will be discarding those since they are unnamed in recount3
bone_marrow_counts <- gtex_transformed_counts$BONE_MARROW %>% as.data.frame()
```

```{r}
gtex_transformed_counts_join <- adipose_tissue_counts %>% left_join(muscle_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(blood_vessel_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(heart_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(ovary_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(uterus_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(vagina_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(breast_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(skin_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(salivary_gland_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(brain_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(adrenal_gland_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(thyroid_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(lung_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(spleen_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(pancreas_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(esophagus_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(stomach_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(colon_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(small_intestine_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(prostate_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(testis_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(nerve_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(pituitary_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(blood_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(liver_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(kidney_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(cervix_uteri_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(fallopian_tube_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(bladder_counts, by = "gene_id")
#gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(study_na_counts, by = "gene_id")
gtex_transformed_counts_join <- gtex_transformed_counts_join %>% left_join(bone_marrow_counts, by = "gene_id")

gtex_data_final <- read_csv("gtex_data_final.csv", col_types = cols(...1 = col_skip()))
gtex_data_final$external_id <- gsub("-", ".", gtex_data_final$external_id)

#Finding which data is in both eyeIntegration and recount3
gtex_keep <- intersect(names(gtex_transformed_counts_join), gtex_data_final$external_id) #The gtex_final_data is an object created in the GTEX BigWig Files Script

#Selecting necessary GTEX samples
gtex_transformed_counts_final <- gtex_transformed_counts_join %>% select(one_of(c("gene_id", gtex_keep)))
```

```{r}
write.csv(gtex_transformed_counts_final, file="gene_counts/gtex_transformed_counts.csv")
```
