---
title: "make_2022_sqlite_db"
author: "Prashit Parikh"
date: "3/1/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSQLite)
library(tidyverse)
library(pool)
library(dplyr)
library(readr)
library(rtracklayer)
library(dtplyr)
```

```{r}
#Function for splitting data and left_joining gene names

split_gene_join <- function(data_frame, metadata, piece, total_pieces = 10) {
  
  df <- data_frame
  chunk_size <- floor(nrow(data_frame)/total_pieces)
  
  start_coordinate = chunk_size * piece

  
  end_coordinate = (start_coordinate + chunk_size) -1
  
  if ((piece + 1) == total_pieces){
    end_coordinate = nrow(data_frame)
  }
  
  start_coordinate
  end_coordinate
  
  sub_df <- df[c(start_coordinate:end_coordinate), ]
  output <- sub_df %>% left_join(metadata, by = "gene_id")
  
  if (dim(sub_df) != dim(output)){
    print(dim(sub_df))
    print(dim(output))
  }
  return(output)
}
```

```{r}
setwd('/Users/parikhpp/git/eyeIntegration_app/ppeyeIntegration/')

gene_counts <- read_csv("~/git/eyeIntegration_app/ppeyeIntegration/gene_counts.csv")

annotations <- rtracklayer::import("~/recount3/recount3_local/human/annotations/gene_sums/human.gene_sums.G029.gtf.gz")
annotations2 <- rtracklayer::import("~/recount3/recount3_local/human/annotations/gene_sums/human.gene_sums.G026.gtf.gz")
annotations_df <- as.data.frame(annotations)
annotations_exon <- rtracklayer::import("~/recount3/recount3_local/human/annotations/exon_sums/human.exon_sums.G029.gtf.gz")
annotations_exon_df <- as.data.frame(annotations_exon)
metadata <- read_csv("~/NEI Projects/combined_metadata.csv", col_types = cols(...1 = col_skip()))

#Dropping duplicate colnames prior to left_join
annotations_exon_df <- annotations_exon_df %>% select(-c(seqnames, strand, phase, gene_name, tag, start, source, level, end, type, havana_gene, width, score, gene_type))
gene_data <- annotations_df %>% left_join(annotations_exon_df, by="gene_id")
gene_data_join <- gene_data[,c(10,12)] %>% unique()

gene_pool_2022 <- dbConnect(RSQLite::SQLite(), dbname = "eyeIntegration_2022_human.sqlite")

#Left_joining gene_name to gene_counts
gene_counts_1 <- split_gene_join(gene_counts, gene_data_join, 0)
gene_counts_2 <- split_gene_join(gene_counts, gene_data_join, 1)
gene_counts_3 <- split_gene_join(gene_counts, gene_data_join, 2)
gene_counts_4 <- split_gene_join(gene_counts, gene_data_join, 3)
gene_counts_5 <- split_gene_join(gene_counts, gene_data_join, 4)
gene_counts_6 <- split_gene_join(gene_counts, gene_data_join, 5)
gene_counts_7 <- split_gene_join(gene_counts, gene_data_join, 6)
gene_counts_8 <- split_gene_join(gene_counts, gene_data_join, 7)
gene_counts_9 <- split_gene_join(gene_counts, gene_data_join, 8)
gene_counts_10 <- split_gene_join(gene_counts, gene_data_join, 9)

gene_counts_name <- rbind(gene_counts_1, gene_counts_2, gene_counts_3, gene_counts_4, gene_counts_5, gene_counts_6, gene_counts_7, gene_counts_8, gene_counts_9, gene_counts_10)
names(gene_counts_name) <- c("sample_accession", "gene_id", "value", "gene_name")

#make gene ID df
gene_IDs <- gene_data %>% dplyr::select(gene_name, gene_type) %>% arrange(gene_name) %>% unique()
names(gene_IDs) <- c("ID", "gene_type")

#make tx ID df
gene_data <- gene_data %>% mutate(tx_name = paste(gene_data$transcript_name, paste("(", gene_data$transcript_id, ")", sep="")))
tx_IDs <- gene_data %>% dplyr::select(tx_name, transcript_type) %>% arrange(tx_name) %>% unique()
names(tx_IDs) <- c("ID", "transcript_type")

#Calculate mean_rank_deciles for genes by sub_tissue
names(gene_counts_name) <- c("sample_accession", "gene_id", "value", "ID")
lsTPM_gene <- gene_counts_name %>% select(sample_accession, value, ID)

#Calculating Mean Rank Decile
mean_rank_decile <- lsTPM_gene %>% 
  left_join(.,metadata, by = "sample_accession") %>% 
  arrange(-value, Sub_Tissue) %>% 
  dplyr::select(Sub_Tissue, sample_accession, ID, value ) %>% 
  group_by(Sub_Tissue, ID) %>% summarise(meanlsTPM = mean(value)) %>% 
  mutate(Rank = rank(-meanlsTPM, ties.method='first'), Decile = ntile(meanlsTPM, n = 10)) %>% 
  arrange(Sub_Tissue, Rank)

#Writing the tables
dbWriteTable(gene_pool_2022, 'mean_rank_decile_gene', mean_rank_decile, row.names = FALSE, overwrite = TRUE)
db_create_index(gene_pool_2022,'mean_rank_decile_gene', 'ID')

dbWriteTable(gene_pool_2022, 'lsTPM_gene', lsTPM_gene, row.names = FALSE, overwrite = TRUE)
db_create_index(gene_pool_2022, 'lsTPM_gene', 'ID')

dbWriteTable(gene_pool_2022, 'metadata', metadata, row.names = FALSE, overwrite = TRUE)

dbWriteTable(gene_pool_2022, 'tx_IDs', tx_IDs, row.names = FALSE, overwrite = TRUE)
db_create_index(gene_pool_2022, 'tx_IDs', 'ID')

dbWriteTable(gene_pool_2022, 'gene_IDs', gene_IDs, row.names = FALSE, overwrite = TRUE)
db_create_index(gene_pool_2022, 'gene_IDs', 'ID')

dbWriteTable(gene_pool_2022, 'Date_DB_Created', Sys.Date() %>% as.character() %>% enframe(name = NULL) %>% select(DB_Created = value), row.names = FALSE, overwrite=TRUE)
```