---
title: "recount3_data_transformations"
author: "Prashit Parikh"
date: "4/10/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tibble)
#BiocManager::install("recount")
library(recount)
library(readr)
library(recount3)
recount3_cache_rm()
options(recount3_url = "http://duffel.rail.bio/recount3/")
hp<-available_projects()
```

```{r}
eyeIntegration19 <- read_delim("https://hpc.nih.gov/~mcgaugheyd/eyeIntegration/2019_metadata_04.tsv.gz", "\t", escape_double = FALSE, trim_ws = TRUE)

recount3_transformed_counts <- list()
projects_local <- c("SRP002881", "SRP011895", "SRP012585", "SRP015336", "SRP016140", "SRP034875",
                    "SRP035641", "SRP045639", "SRP053034", "SRP055101", "SRP061670", "SRP062870",
                    "SRP064956", "SRP070148", "SRP075990", "SRP079002", "SRP080002", "SRP090226",
                    "SRP091605", "SRP091675", "SRP092413", "SRP093877", "SRP094572", "SRP097696",
                    "SRP098761", "SRP105756", "SRP106457", "SRP108292", "SRP110135", "SRP111145",
                    "SRP115908", "SRP117613", "SRP119291", "SRP119766", "SRP151763", 
                    "SRP159246", "ERP022243")

for (i in projects_local) {
  rse_gene = create_rse_manual(i, annotation = "gencode_v29")
  assays(rse_gene)$counts <- transform_counts(rse_gene)
  
  rse_gene_counts <- recount::getTPM(rse_gene) %>% data.frame()
  rse_gene_counts <- rownames_to_column(rse_gene_counts, var = "gene_id")
  
  recount3_transformed_counts[[i]] <- rse_gene_counts
}

SRP002881_counts <- recount3_transformed_counts$SRP002881 %>% as.data.frame()
SRP011895_counts <- recount3_transformed_counts$SRP011895 %>% as.data.frame()
SRP012585_counts <- recount3_transformed_counts$SRP012585 %>% as.data.frame()
SRP015336_counts <- recount3_transformed_counts$SRP015336 %>% as.data.frame()
SRP016140_counts <- recount3_transformed_counts$SRP016140 %>% as.data.frame()
SRP034875_counts <- recount3_transformed_counts$SRP034875 %>% as.data.frame()
SRP035641_counts <- recount3_transformed_counts$SRP035641 %>% as.data.frame()
SRP045639_counts <- recount3_transformed_counts$SRP045639 %>% as.data.frame()
SRP053034_counts <- recount3_transformed_counts$SRP053034 %>% as.data.frame()
SRP055101_counts <- recount3_transformed_counts$SRP055101 %>% as.data.frame()
SRP061670_counts <- recount3_transformed_counts$SRP061670 %>% as.data.frame()
SRP062870_counts <- recount3_transformed_counts$SRP062870 %>% as.data.frame()
SRP064956_counts <- recount3_transformed_counts$SRP064956 %>% as.data.frame()
SRP070148_counts <- recount3_transformed_counts$SRP070148 %>% as.data.frame()
SRP075990_counts <- recount3_transformed_counts$SRP075990 %>% as.data.frame()
SRP079002_counts <- recount3_transformed_counts$SRP079002 %>% as.data.frame()
SRP080002_counts <- recount3_transformed_counts$SRP080002 %>% as.data.frame()
#SRP090027_counts <- recount3_transformed_counts$SRP090027 %>% as.data.frame()
#SRP090040_counts <- recount3_transformed_counts$SRP090040 %>% as.data.frame()
SRP090226_counts <- recount3_transformed_counts$SRP090226 %>% as.data.frame()
SRP091605_counts <- recount3_transformed_counts$SRP091605 %>% as.data.frame()
SRP091675_counts <- recount3_transformed_counts$SRP091675 %>% as.data.frame()
SRP092413_counts <- recount3_transformed_counts$SRP092413 %>% as.data.frame()
SRP093877_counts <- recount3_transformed_counts$SRP093877 %>% as.data.frame()
SRP094572_counts <- recount3_transformed_counts$SRP094572 %>% as.data.frame()
SRP097696_counts <- recount3_transformed_counts$SRP097696 %>% as.data.frame()
SRP098761_counts <- recount3_transformed_counts$SRP098761 %>% as.data.frame()
SRP105756_counts <- recount3_transformed_counts$SRP105756 %>% as.data.frame()
SRP106457_counts <- recount3_transformed_counts$SRP106457 %>% as.data.frame()
SRP108292_counts <- recount3_transformed_counts$SRP108292 %>% as.data.frame()
SRP110135_counts <- recount3_transformed_counts$SRP110135 %>% as.data.frame()
SRP111145_counts <- recount3_transformed_counts$SRP111145 %>% as.data.frame()
SRP115908_counts <- recount3_transformed_counts$SRP115908 %>% as.data.frame()
SRP117613_counts <- recount3_transformed_counts$SRP117613 %>% as.data.frame()
SRP119291_counts <- recount3_transformed_counts$SRP119291 %>% as.data.frame()
SRP119766_counts <- recount3_transformed_counts$SRP119766 %>% as.data.frame()
SRP151763_counts <- recount3_transformed_counts$SRP151763 %>% as.data.frame()
SRP159246_counts <- recount3_transformed_counts$SRP159246 %>% as.data.frame()
ERP022243_counts <- recount3_transformed_counts$ERP022243 %>% as.data.frame()

recount3_transformed_counts <- ERP022243_counts %>% left_join(SRP002881_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP011895_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP012585_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP015336_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP016140_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP034875_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP035641_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP045639_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP053034_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP055101_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP061670_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP062870_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP064956_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP070148_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP075990_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP079002_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP080002_counts, by="gene_id")
#recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP090027_counts, by="gene_id")
#recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP090040_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP090226_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP091605_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP091675_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP092413_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP093877_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP094572_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP097696_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP098761_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP105756_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP106457_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP108292_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP110135_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP111145_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP115908_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP117613_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP119291_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP119766_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP151763_counts, by="gene_id")
recount3_transformed_counts <- recount3_transformed_counts %>% left_join(SRP159246_counts, by="gene_id")

keep <- intersect(names(recount3_transformed_counts), eyeIntegration19$run_accession)

recount3_transformed_counts <- recount3_transformed_counts %>% select(one_of(c("gene_id", keep)))

write.csv(recount3_transformed_counts, file="gene_counts/recount3_transformed_counts.csv")
```