---
title: "Track Hub"
author: "Prashit Parikh"
date: "2/15/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("readxl")
library(readxl)
#install.packages("stringr")
library(stringr)
#install.packages("glue")
library(glue)
#install.packages("dplyr)
library(dplyr)
#install.packages("readr")
library(readr)
```

```{r}
#Large-Scale Track Info
track_data <- read_excel("TrackHubData.xlsx")
track_data <- track_data %>% mutate(run_accession = str_extract(bigwigs, ".RR\\d+"))
track_data <- track_data %>% mutate(gtex_external_id_a = str_extract(bigwigs, "GTEX-[A-Z0-9]+-[0-9]+-SM-[A-Z0-9]+"))
track_data <- track_data %>% mutate(gtex_external_id_b = 
                                      str_extract(bigwigs, "GTEX-[A-Z0-9]+-[0-9]+-[a-zA-Z0-9]+-SM-[A-Z0-9]+"))
track_data <- track_data %>% mutate(gtex_external_id_c = str_extract(bigwigs, "K-[A-Z0-9]+-SM-[A-Z0-9]+"))
track_data <- track_data %>% mutate(gtex_external_id = ifelse((is.na(gtex_external_id_a)), ifelse((is.na(gtex_external_id_b)), gtex_external_id_c, gtex_external_id_b), gtex_external_id_a))

track_data <- track_data %>% select(bigwigs, run_accession, gtex_external_id)

combined_metadata <- read_csv("combined_metadata.csv", col_types = cols(...1 = col_skip()))
combined_metadata <- combined_metadata %>% mutate(gtex_external_id_a = str_extract
                                                  (sample_attribute, "GTEX-[A-Z0-9]+-[0-9]+-SM-[A-Z0-9]+"))
combined_metadata <- combined_metadata %>% mutate(gtex_external_id_b = 
                                      str_extract(sample_attribute, "GTEX-[A-Z0-9]+-[0-9]+-[a-zA-Z0-9]+-SM-[A-Z0-9]+"))
combined_metadata <- combined_metadata %>% mutate(gtex_external_id_c = str_extract(sample_attribute, "K-[A-Z0-9]+-SM-[A-Z0-9]+"))
combined_metadata <- combined_metadata %>% mutate(gtex_external_id = ifelse((is.na(gtex_external_id_a)), ifelse((is.na(gtex_external_id_b)), gtex_external_id_c, gtex_external_id_b), gtex_external_id_a))

#Joining the urls to the remaining metadata
track_data_gtex <- track_data[is.na(track_data$run_accession),]
track_data_sra <- track_data[is.na(track_data$gtex_external_id),]

track_data_gtex <- track_data_gtex[,c(1,3)] %>% left_join(combined_metadata[,c(10,17)], by="gtex_external_id")

track_data <- rbind(track_data_gtex, track_data_sra)

track_data <- track_data %>% left_join(combined_metadata[,c(1:13)], by = "run_accession")
track_data <- track_data[!duplicated(track_data$run_accession), ]

track_data$Sub_Tissue_parent <- str_replace_all(track_data$Sub_Tissue, " - ", "_")
track_data$Sub_Tissue_parent <- str_replace_all(track_data$Sub_Tissue_parent, " ", "_")
track_data$Sub_Tissue_parent <- str_replace_all(track_data$Sub_Tissue_parent, "/", "_")

#Remove new organoid and choroid plexus data as it is only comprised of one study
track_data <- track_data %>% filter(Sub_Tissue != "WIBR3 hESC Choroid plexus Organoids")
track_data <- track_data %>% filter(Sub_Tissue != "Choroid Plexus - Cell Line")

track_data <- track_data %>% mutate(parent_track = glue(
"

track {Sub_Tissue_parent}
container multiWig
shortLabel {Sub_Tissue_parent}
longLabel {Sub_Tissue_parent}
type bigWig 0 30000
viewLimits 0:100
visibility full
maxHeightPixels 150:30:11
aggregate transparentOverlay
showSubtrackColorOnUi on
windowingFunction mean
priority 1.4
configurable on
autoScale on

"))

track_data <- track_data %>% mutate(parent_track_sample_level = glue(
"

track {Sub_Tissue_parent}
container multiWig
shortLabel {Sub_Tissue_parent}
longLabel {Sub_Tissue_parent}
type bigWig 0 30000
viewLimits 0:100
visibility full
maxHeightPixels 150:30:11
aggregate none
showSubtrackColorOnUi on
windowingFunction mean
priority 1.4
configurable on
autoScale on

"))

#Create URLs
track_data <- track_data %>% mutate(url = paste("https://hpc.nih.gov/~parikhpp/combined/",{bigwigs}, sep = ""))
```

```{r}
track_data <- track_data %>% mutate(track_file = glue(
"

track {run_accession}
bigDataUrl {url}
shortLabel {run_accession}
longLabel {run_accession}
parent {Sub_Tissue_parent}
type bigWig
color 180, 102, 255"))
```

```{r}
track_file_function <- function(sub_tissue, file_name, file_name_sample) {

write(rbind(track_data$parent_track[which(track_data$Sub_Tissue_parent==sub_tissue)[1]],
          paste(track_data$track_file[which(track_data$Sub_Tissue_parent==sub_tissue)], collapse = "\n")), 
      file = file_name)

write(rbind(track_data$parent_track_sample_level[which(track_data$Sub_Tissue_parent==sub_tissue)[1]],
          paste(track_data$track_file[which(track_data$Sub_Tissue_parent==sub_tissue)], collapse = "\n")),
      file = file_name_sample)
}
```

```{r}
sub_tissue <- names(table(track_data$Sub_Tissue_parent))

for (i in 1:length(sub_tissue)) {
track_file_function(sub_tissue[i], paste("Track_Files/", sub_tissue[i], "_Track.txt", sep = ""), paste("Track_Files/", sub_tissue[i], "_sample_Track.txt", sep = ""))
}
```